fix ase.build.make_supercell bug. Extend MC NumpyEncoder
The make_supercell method of ASE has had a bug from version 3.18.0 (still in actual version 3.22.0). I have created an issue in ASEs git repo. Until this is fixed in ASE, I have added a fixed version of make_supercell in cllusterx/utils.py. Now clusterx/super_cell.py is using this fixed version instead of ASEs to create supercells.
Thanks to this fix, now clusterx works fine with the latest version of ASE, thus I modified the setup.py to remove the version constraint in ASE (it was before compatible only with 3.17.0).

The test_metropolis.py started to fail with the error:

>       elif isinstance(obj,(Atoms.cell.Cell,)):
E       AttributeError: 'property' object has no attribute 'Cell'

in the NumpyEncoder class of the clusterx/monte_carlo.py method. I fixed it by adding the type ase.Cell to the numpyEncoder in clusterx/monte_carlo.py.